server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: auto_template
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
